import { chromium } from 'playwright';
const errors = [];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1280, height: 720 } });
page.on('console', (msg) => { if (msg.type() === 'error') errors.push(msg.text()); });
page.on('pageerror', (err) => errors.push('pageerror: ' + err.message));
await page.goto('http://localhost:8080/index.html', { waitUntil: 'load' });
await page.evaluate(() => { document.getElementById('world-new-btn').click(); });
await page.waitForTimeout(800);
await page.evaluate(() => document.querySelector('.world-info').click());
await page.waitForTimeout(300);
await page.evaluate(() => window.__setRunning(false));
await page.evaluate(() => { window.__forceMode('car'); window.__setVehiclePos('car', 0, 0, 0, 0); });
await page.evaluate(() => window.__setKeys({ up: true, shift: true }));
await page.evaluate(() => window.__stepFrames(90));
const d = await page.evaluate(() => window.__debug().car);
console.log('boosting:', d.boosting, 'speed:', d.speed);
console.log('PASS:', d.boosting === true);
console.log('ERRORS:', errors.length ? errors.join('\n') : 'none');
await browser.close();
